### ISSUE TITLE
Docker Link host - Error: double colon in host identifier

### ISSUE THREAD

**Issue by Css-IanM** [SierraSoftworks/Iridium#96]
I'm trying to run my server in a docker container. I'm setting the host as the container link and im seeing this error
`Error: double colon in host identifier`
```
export const mongoUser = new UserDatabase({ host: 'mongodb', port: 27017, database: 'test_db'});
```
Here is the link alias as `mongodb` as shown in the host property above.
```
version: '3'
services:
  api:
    image: central_server
    build: .
    ports:
     [ "5001:5001"]
    links:
     - "mongodb"
  mongodb:
    image: "mongo:latest"
    ports: 
     ["27017:27017"]
```

is there some quirk in the connection string builder i'm not seeing that's causing a malformed URI?
